# Generated by Django 5.2.8 on 2025-11-21 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('fecha_siembra', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EtapaCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='cultivos.cultivo')),
            ],
        ),
    ]
