# Generated by Django 5.2.8 on 2025-11-21 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Riego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad_litros', models.FloatField()),
                ('frecuencia', models.CharField(choices=[('diario', 'Diario'), ('interdiario', 'Interdiario'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal')], max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riegos', to='cultivos.cultivo')),
            ],
        ),
    ]
